language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t g0retex/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true g0retex/react-test npm test

after_success:
 - docker build -t g0retex/multi-client ./client
 - docker build -t g0retex/multi-nginx ./nginx
 - docker build -t g0retex/multi-server ./server
 - docker build -t g0retex/multi-worker ./worker
# Log in to the Docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take Those Images and Push Them to Docker Hub
 - docker push -t g0retex/multi-client
 - docker push -t g0retex/multi-nginx
 - docker push -t g0retex/multi-server
 - docker push -t g0retex/multi-worker
